- name: Copy mongodb repo # ansible copy module
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongodb # ansible install package
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: start and enable mongodb # ansible systemctl module
  ansible.builtin.service:
    name: mongod 
    state: started
    enabled: yes 

- name: alow remote conncetions # ansible systemctl start module
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: ' 0.0.0.0' 


- name: start and enable mongodb
  ansible.builtin.service:
    name: mongod
    state: restarted 