- name: app setup
  ansible.builtin.import_role:
   name: common
   tasks_from: app-setup

- name: app nodejs
  ansible.builtin.import_role:
   name: common
   tasks_from: nodejs

- name: mongodb setup
  ansible.builtin.import_role:
   name: common
   tasks_from: mongodb-setup 

- name: service systemd
  ansible.builtin.import_role:
   name: common
   tasks_from: systemd     

- name: app setup
  ansible.builtin.import_role:
   name: common
   tasks_from: app-setup

- name: java
  ansible.builtin.import_role:
   name: common
   tasks_from: java

- name: mysql setup
  ansible.builtin.import_role:
   name: common
   tasks_from: mysql-setup 

- name: service systemd
  ansible.builtin.import_role:
   name: common
   tasks_from: systemd 

  