- name: Add user roboshop # ansible adduseer module
  ansible.builtin.user:
   name: roboshop 

- name: Recursively remove app directory # ansible app directory
  ansible.builtin.file:
   path: /app
   state: directory    

- name: "Download for {{component}} application # ansible download module"
  ansible.builtin.get_url:
   url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
   dest: /tmp

- name: "extract {{component}} application # ansible unarchive module"
  ansible.builtin.copy:
   src: "/tmp/{{component}}.zip"
   dest: /app
   remote_src: yes 
