- name: disable old nodejs and enable nodejs
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

- name: Install nodejs # ansible install nodejs module
  ansible.builtin.dnf:
   name: nodejs
   state: present

- name: Install npm # ansible install depencies
  community.general.npm:
   name: npm
   path: /app   