- name: Copy catalogue service # ansible copy module
  ansible.builtin.copy:
   src: catalogue.service
   dest: /etc/systemd/system/catalogue.service

- name: daemon reload and start # ansible demon module
  ansible.builtin.systemd_service:
   daemon_reload: true

- name: start and enable catalogue
  ansible.builtin.service:
   name: catalogue
   state: restarted
   enabled: yes  

